# Fonts
font_family      Jetbrains Mono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0

# Misc
enable_audio_bell no
shell_integration disabled
confirm_os_window_close 0

#keybinds
# Clear any default bindings and map it to Kitty's native copy mode
map ctrl+shift+a enter_copy_mode

# Cursor
cursor_shape underline
cursor_blink_interval -20
cursor_trail 3

# Looks
background_opacity 0.7
window_margin_width 10

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
