cursor            #ceca75
cursor_text_color #333200

foreground            #e6e2d5
background            #0f0e07
selection_foreground  #323118
selection_background  #cbc8a4
url_color             #cbc8a4

#: black 000000 767676
color0  #14140c
color8  #36352c
#: red cc0403 f2201f
color1  #443a29
color9  #a28b64
#: green 19cb00 23fd00
color2  #cbc8a4
color10 #e8e4bf
#: yellow cecb00 fffd00
color3  #a5d0bb
color11 #c0ecd7
#: blue 0d73cc 1a8fff
color4  #4b4900
color12 #ceca75
#: magenta cb1ed1 fd28ff
color5  #49482c
color13 #cbc8a4
#: cyan 0dcdcd 14ffff
color6  #264e3e
color14 #a5d0bb
#: white dddddd ffffff
color7  #cac7b6
color15 #e6e2d5

mark1_foreground #1e1d00
mark1_background #eae68e
mark2_foreground #1d1c06
mark2_background #e8e4bf
mark3_foreground #002116
mark3_background #c0ecd7

active_tab_foreground #333200
active_tab_background #ceca75
inactive_tab_foreground #eae68e
inactive_tab_background #4b4900

active_border_color #ceca75
inactive_border_color #333200
# bell_border_color #ff5a00
